[build]
command = "npm ci && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "22"
NPM_VERSION = "10"

# Redirect all non-file requests to index.html for React Router
[[redirects]]
from = "/*"
to = "/index.html"
status = 200